[package]
name = "bg7"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.18"
crossterm = "0.23"
plaid = "1"
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
anyhow = "1.0.38"
